service:
  name: melpa-bot-client

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-express

provider:
  name: aws
  runtime: nodejs8.10

functions:
  melpa-bot-client:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: ANY
