service:
  name: melpa-bot-client

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-express

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: handler.app
    events:
      - http:
          method: any
          path: /{proxy+}
